<a href="https://colab.research.google.com/github/shahshail2001/AI-ML-Codes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

In [28]:
a= np.arange(10)
b = np.arange(5)
a[5:] = b[::-1] # b here is the reverse of first five elements.
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [31]:
np.shares_memory(a,b)

True

In [32]:
b[0] = 10
print(b)
print(a) # Here the value of the first element of the a is changed because the b and a are pointing to the same memory location.

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [33]:
a= np.arange(10)
c = a[::2].copy() # Force copy
c

array([0, 2, 4, 6, 8])

In [34]:
np.shares_memory(a,c)

False

# **Fancy Indexing**

In [35]:
a = np.random.randint(0,100,20)
a

array([39, 41, 64, 19, 20, 77, 51, 27,  6, 40, 26, 93, 36, 10, 83, 45, 36,
       88, 31, 54])

In [36]:
# Mask creates copies not views
mask = (a%2==0) # It will generate a masking which will apply to all the array
extract_from_a = a[mask]
extract_from_a

array([64, 20,  6, 40, 26, 36, 10, 36, 88, 54])

In [37]:
a[mask]=-1
a

array([39, 41, -1, 19, -1, 77, 51, 27, -1, -1, -1, 93, -1, -1, 83, 45, -1,
       -1, 31, -1])

In [38]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
a[[2,3,2,4,5,3]]

array([20, 30, 20, 40, 50, 30])

In [40]:
a[[9,7]] = 1000
a

array([   0,   10,   20,   30,   40,   50,   60, 1000,   80, 1000])

In [41]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [42]:
a**2

array([ 1,  4,  9, 16])

In [43]:
b = np.ones(4) + 1
print(b)
a-b

[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [44]:
a*b

array([2., 4., 6., 8.])

In [45]:
c = np.diag([1,2,3,4])
print(c*c)
print('********************')
print(c.dot(c))


[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
********************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [46]:
a = np.array([1,2,3,4,7])
b = np.array([5,2,3,4,8])
a == b

array([False,  True,  True,  True, False])

In [47]:
a>b
a<b

array([ True, False, False, False,  True])

In [48]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])

np.array_equal(a,b)

False

In [49]:
a=np.array([1,0,1,1], dtype=bool)
b=np.array([0,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True, False,  True,  True])

In [50]:
np.logical_and(a,b)

array([False, False,  True, False])

In [51]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [52]:
np.log(a)

<ipython-input-52-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])