NumPy Arrays

In [1]:
import numpy as np
a = np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [2]:
a.ndim


1

In [3]:
a.shape

(4,)

In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
b

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.ndim

2

In [6]:
b.shape

(2, 3)

In [7]:
len(b) #returns the length of the first dimension of the array

2

In [8]:
#3D array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
c.ndim

3

In [10]:
c.shape

(2, 2, 3)

In [11]:
#using the arrange function
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
b = np.arange(1,10,2) # start, end, step
b

array([1, 3, 5, 7, 9])

In [13]:
a = np.linspace(0,1,5) # start, end, number of points in betwee start and end
a

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# common arrays
a = np.ones((3,3)) #tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
c = np.eye(3) # Returns an identity matrix 
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
d = np.eye(3, 2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [18]:
# Create a diagonal matrix
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
# Print the diagonal matrix
np.diag(a)

array([1, 2, 3, 4])

In [20]:
# Create an array of random numbers
a = np.random.rand(4) # uniform distibutated random number
a

array([0.6373602 , 0.49369223, 0.61558806, 0.52145748])

In [21]:
a = np.random.randn(4) # Standard normal variate
a

array([-0.82999152, -0.58912882, -0.54286506, -0.57327167])

In [22]:
a = np.arange(10)
a.dtype
print(a.dtype)
a = np.arange(10,dtype = 'float64') # To specify a perticular data type to the array
a

int32


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
d = np.array([1+2j, 2+3j]) # Complex datatype
print(d)
d.dtype

[1.+2.j 2.+3.j]


dtype('complex128')

In [24]:
b = np.array([True,False,True,False])
print(b)
b.dtype

[ True False  True False]


dtype('bool')

In [25]:
# Accessing the values
a = np.arange(10)
print(a[7])

7


In [26]:
a=np.diag([1,2,3,4])
print(a)
a[3][3]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


4

In [27]:
a[2,1] = 5
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

**Slicing**

In [28]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a[1:8:2] # a[startindex:endindex(exclusive):step]

array([1, 3, 5, 7])

In [30]:
b = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])